/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package deliverymanagementsystem;


import java.awt.Component;
import java.io.*;
import javax.swing.*;
import java.text.SimpleDateFormat;
import java.time.*;


public class DeliverySystem extends javax.swing.JFrame {
delivery_functions df = new delivery_functions();
Customer c = new Customer();
private Component frame;
LocalDate d = LocalDate.now();
    /**
     * Creates new form DeliverySystem
     */
    public DeliverySystem() {
        initComponents();
        jdbc.sqlite();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sendingButtongroup = new javax.swing.ButtonGroup();
        OrderbuttonGroup = new javax.swing.ButtonGroup();
        SysTabbedPane = new javax.swing.JTabbedPane();
        CustrPanel = new javax.swing.JPanel();
        RegButton = new javax.swing.JButton();
        ExitButton = new javax.swing.JButton();
        EditButton = new javax.swing.JButton();
        PayButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        custTable = new javax.swing.JTable();
        viewbutton = new javax.swing.JButton();
        idtxtbox = new javax.swing.JTextField();
        searchbyid = new javax.swing.JButton();
        jLabel26 = new javax.swing.JLabel();
        orderTabbedPane = new javax.swing.JTabbedPane();
        orderPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        custTypeComboBox = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        MemIdField = new javax.swing.JTextField();
        SenderPanel1 = new javax.swing.JPanel();
        senderstate = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        sendername = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        senderphone = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        senderaddr = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        sendercity = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        senderemail = new javax.swing.JTextField();
        DescrPanel = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        weightordertxt = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        pckgcomboBox = new javax.swing.JComboBox();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        GrosstotalLabel = new javax.swing.JLabel();
        taxLabel = new javax.swing.JLabel();
        grandtotalLabel = new javax.swing.JLabel();
        ratelabel = new javax.swing.JLabel();
        rateComboBox = new javax.swing.JComboBox();
        calculate = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        quotalabel = new javax.swing.JLabel();
        sendingInstPanel = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        InstrComboBox = new javax.swing.JComboBox();
        orderoptionpanel = new javax.swing.JPanel();
        sendRadio = new javax.swing.JRadioButton();
        StandingRadioButton = new javax.swing.JRadioButton();
        invoiceButton = new javax.swing.JButton();
        CnclButton = new javax.swing.JButton();
        SearchButton = new javax.swing.JButton();
        RecieverPanel = new javax.swing.JPanel();
        recieverstate = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        recipientname = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        recieverphone = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        recieveraddr = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        recievercity = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        recieveremail = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        ordernum = new javax.swing.JLabel();
        currentdate = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        deliverydate = new javax.swing.JLabel();
        standingOrderPanel = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        memberidfield = new javax.swing.JTextField();
        searchbutton = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        standingTable = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        RecieverPanel1 = new javax.swing.JPanel();
        recieverstate1 = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        recipientname1 = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        recieverphone1 = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        recieveraddr1 = new javax.swing.JTextArea();
        jLabel33 = new javax.swing.JLabel();
        recievercity1 = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        recieveremail1 = new javax.swing.JTextField();
        sendingInstPanel1 = new javax.swing.JPanel();
        jLabel36 = new javax.swing.JLabel();
        InstrComboBox1 = new javax.swing.JComboBox();
        orderoptionpanel1 = new javax.swing.JPanel();
        sendRadio1 = new javax.swing.JRadioButton();
        StandingRadioButton1 = new javax.swing.JRadioButton();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        currentdate1 = new javax.swing.JLabel();
        deliverydate1 = new javax.swing.JLabel();
        invoiceButton1 = new javax.swing.JButton();
        CnclButton1 = new javax.swing.JButton();
        jLabel39 = new javax.swing.JLabel();
        searchorder = new javax.swing.JButton();
        orderid = new javax.swing.JTextField();
        deleteorder = new javax.swing.JButton();
        InvoicePanel = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        textSearchID = new javax.swing.JTextField();
        buttonGetInvoice = new javax.swing.JButton();
        buttonSaveInvoice = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        invoicearea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        RegButton.setText("Register New Member");
        RegButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegButtonActionPerformed(evt);
            }
        });

        ExitButton.setForeground(java.awt.Color.red);
        ExitButton.setText("Exit");
        ExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitButtonActionPerformed(evt);
            }
        });

        EditButton.setText("Edit Details");
        EditButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditButtonActionPerformed(evt);
            }
        });

        PayButton.setText("Payment Details");
        PayButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PayButtonActionPerformed(evt);
            }
        });

        custTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Member Id", "Name", "Phone", "ID NO.", "Email", "Address", "City", "State", "Package"
            }
        ));
        jScrollPane1.setViewportView(custTable);

        viewbutton.setText("View Members");
        viewbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewbuttonActionPerformed(evt);
            }
        });

        searchbyid.setText("Search");
        searchbyid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchbyidActionPerformed(evt);
            }
        });

        jLabel26.setText("Search by ID: ");

        javax.swing.GroupLayout CustrPanelLayout = new javax.swing.GroupLayout(CustrPanel);
        CustrPanel.setLayout(CustrPanelLayout);
        CustrPanelLayout.setHorizontalGroup(
            CustrPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CustrPanelLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(CustrPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(CustrPanelLayout.createSequentialGroup()
                        .addGap(328, 328, 328)
                        .addComponent(jLabel26)
                        .addGap(78, 78, 78)
                        .addComponent(idtxtbox, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54)
                        .addComponent(searchbyid)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 178, Short.MAX_VALUE)
                        .addComponent(viewbutton))
                    .addGroup(CustrPanelLayout.createSequentialGroup()
                        .addGroup(CustrPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(RegButton, javax.swing.GroupLayout.DEFAULT_SIZE, 314, Short.MAX_VALUE)
                            .addComponent(EditButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(PayButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ExitButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(83, 83, 83)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 612, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 188, Short.MAX_VALUE))
        );
        CustrPanelLayout.setVerticalGroup(
            CustrPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CustrPanelLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(CustrPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CustrPanelLayout.createSequentialGroup()
                        .addComponent(RegButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(EditButton, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(PayButton, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(ExitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 463, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(64, 64, 64)
                .addGroup(CustrPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(viewbutton)
                    .addComponent(searchbyid)
                    .addComponent(idtxtbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26))
                .addContainerGap(176, Short.MAX_VALUE))
        );

        SysTabbedPane.addTab("Customer Management", CustrPanel);

        jLabel1.setText("Select Client Type: ");

        custTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Non-member", "Member" }));
        custTypeComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                custTypeComboBoxItemStateChanged(evt);
            }
        });
        custTypeComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                custTypeComboBoxActionPerformed(evt);
            }
        });

        jLabel2.setText("Member ID: ");

        MemIdField.setEnabled(false);
        MemIdField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MemIdFieldActionPerformed(evt);
            }
        });

        SenderPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Sender "));

        jLabel17.setText("Name:");

        jLabel24.setText("Phone No:");

        jLabel10.setText("Address:");

        senderaddr.setColumns(20);
        senderaddr.setRows(5);
        jScrollPane3.setViewportView(senderaddr);

        jLabel6.setText("City: ");

        jLabel7.setText("State:");

        jLabel8.setText("E-Mail: ");

        senderemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                senderemailActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout SenderPanel1Layout = new javax.swing.GroupLayout(SenderPanel1);
        SenderPanel1.setLayout(SenderPanel1Layout);
        SenderPanel1Layout.setHorizontalGroup(
            SenderPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SenderPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(SenderPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SenderPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(SenderPanel1Layout.createSequentialGroup()
                        .addGroup(SenderPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(SenderPanel1Layout.createSequentialGroup()
                                .addGroup(SenderPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel24)
                                    .addComponent(jLabel10))
                                .addGap(58, 58, 58)
                                .addGroup(SenderPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(sendername)
                                    .addComponent(senderphone)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)))
                            .addGroup(SenderPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(68, 68, 68)
                                .addGroup(SenderPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(sendercity, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                                    .addComponent(senderstate)
                                    .addComponent(senderemail))))
                        .addContainerGap())
                    .addGroup(SenderPanel1Layout.createSequentialGroup()
                        .addGroup(SenderPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel6))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        SenderPanel1Layout.setVerticalGroup(
            SenderPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SenderPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(SenderPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(sendername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(SenderPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(senderphone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(SenderPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addGroup(SenderPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(sendercity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(SenderPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(senderstate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(SenderPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(senderemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34))
        );

        DescrPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Description of Content"));

        jLabel21.setText("Order Weight:");

        weightordertxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                weightordertxtActionPerformed(evt);
            }
        });

        jLabel23.setText("Type Of Package:");

        jLabel22.setText("Payment Amount:");

        pckgcomboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Letter", "Parcel" }));

        jLabel12.setText("Rate:");

        jLabel13.setText("Gross Total:");

        jLabel14.setText("Tax:");

        rateComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Standard", "Basic", "Premium", "Gold" }));

        calculate.setText("Calculate");
        calculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculateActionPerformed(evt);
            }
        });

        jLabel25.setText("Delivery Limit:");

        javax.swing.GroupLayout DescrPanelLayout = new javax.swing.GroupLayout(DescrPanel);
        DescrPanel.setLayout(DescrPanelLayout);
        DescrPanelLayout.setHorizontalGroup(
            DescrPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DescrPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(DescrPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DescrPanelLayout.createSequentialGroup()
                        .addGroup(DescrPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel21)
                            .addGroup(DescrPanelLayout.createSequentialGroup()
                                .addGap(104, 104, 104)
                                .addComponent(weightordertxt, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(DescrPanelLayout.createSequentialGroup()
                                .addGroup(DescrPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel23)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel14))
                                .addGap(18, 18, 18)
                                .addGroup(DescrPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(pckgcomboBox, 0, 93, Short.MAX_VALUE)
                                    .addComponent(taxLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(GrosstotalLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(DescrPanelLayout.createSequentialGroup()
                                .addGroup(DescrPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12)
                                    .addGroup(DescrPanelLayout.createSequentialGroup()
                                        .addGap(55, 55, 55)
                                        .addComponent(rateComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addComponent(ratelabel, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(quotalabel, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(23, Short.MAX_VALUE))
                    .addGroup(DescrPanelLayout.createSequentialGroup()
                        .addComponent(jLabel22)
                        .addGap(18, 18, 18)
                        .addComponent(grandtotalLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(calculate)
                        .addGap(32, 32, 32))))
        );
        DescrPanelLayout.setVerticalGroup(
            DescrPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DescrPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(DescrPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(weightordertxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(DescrPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(pckgcomboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(DescrPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(DescrPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(calculate))
                    .addGroup(DescrPanelLayout.createSequentialGroup()
                        .addGroup(DescrPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(DescrPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(DescrPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel12)
                                    .addComponent(rateComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DescrPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel25)
                                    .addComponent(quotalabel, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(ratelabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(DescrPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(GrosstotalLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(DescrPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(DescrPanelLayout.createSequentialGroup()
                                .addComponent(taxLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(grandtotalLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(DescrPanelLayout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel22)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)))
                .addContainerGap())
        );

        sendingInstPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Sending Instructions"));

        jLabel11.setText("In case of non-delivery:");

        InstrComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Return to sender", "Contact for redirect" }));

        javax.swing.GroupLayout sendingInstPanelLayout = new javax.swing.GroupLayout(sendingInstPanel);
        sendingInstPanel.setLayout(sendingInstPanelLayout);
        sendingInstPanelLayout.setHorizontalGroup(
            sendingInstPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sendingInstPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(sendingInstPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(InstrComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(98, Short.MAX_VALUE))
        );
        sendingInstPanelLayout.setVerticalGroup(
            sendingInstPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sendingInstPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(InstrComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        orderoptionpanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Order Options"));

        OrderbuttonGroup.add(sendRadio);
        sendRadio.setText("Send Order Immediately");
        sendRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendRadioActionPerformed(evt);
            }
        });

        OrderbuttonGroup.add(StandingRadioButton);
        StandingRadioButton.setText("Standing Order");
        StandingRadioButton.setEnabled(false);
        StandingRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StandingRadioButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout orderoptionpanelLayout = new javax.swing.GroupLayout(orderoptionpanel);
        orderoptionpanel.setLayout(orderoptionpanelLayout);
        orderoptionpanelLayout.setHorizontalGroup(
            orderoptionpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(orderoptionpanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(orderoptionpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sendRadio)
                    .addComponent(StandingRadioButton))
                .addContainerGap(118, Short.MAX_VALUE))
        );
        orderoptionpanelLayout.setVerticalGroup(
            orderoptionpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(orderoptionpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(sendRadio)
                .addGap(18, 18, 18)
                .addComponent(StandingRadioButton)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        invoiceButton.setText("Save Order");
        invoiceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                invoiceButtonActionPerformed(evt);
            }
        });

        CnclButton.setText("Cancel");
        CnclButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CnclButtonActionPerformed(evt);
            }
        });

        SearchButton.setText("Search");
        SearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchButtonActionPerformed(evt);
            }
        });

        RecieverPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Reciever"));

        jLabel16.setText("Name:");

        jLabel20.setText("Phone No:");

        jLabel9.setText("Address:");

        recieveraddr.setColumns(20);
        recieveraddr.setRows(5);
        jScrollPane2.setViewportView(recieveraddr);

        jLabel3.setText("City: ");

        jLabel4.setText("State:");

        jLabel5.setText("E-Mail: ");

        javax.swing.GroupLayout RecieverPanelLayout = new javax.swing.GroupLayout(RecieverPanel);
        RecieverPanel.setLayout(RecieverPanelLayout);
        RecieverPanelLayout.setHorizontalGroup(
            RecieverPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RecieverPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(RecieverPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(RecieverPanelLayout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(RecieverPanelLayout.createSequentialGroup()
                        .addGroup(RecieverPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(RecieverPanelLayout.createSequentialGroup()
                                .addGroup(RecieverPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel20)
                                    .addComponent(jLabel9))
                                .addGap(58, 58, 58)
                                .addGroup(RecieverPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(recipientname)
                                    .addComponent(recieverphone)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)))
                            .addGroup(RecieverPanelLayout.createSequentialGroup()
                                .addGroup(RecieverPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addGap(68, 68, 68)
                                .addGroup(RecieverPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(recievercity, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                                    .addComponent(recieverstate)
                                    .addComponent(recieveremail))))
                        .addContainerGap())
                    .addGroup(RecieverPanelLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        RecieverPanelLayout.setVerticalGroup(
            RecieverPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RecieverPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(RecieverPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(recipientname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(RecieverPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(recieverphone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(RecieverPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(RecieverPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(recievercity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(RecieverPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(recieverstate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(RecieverPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(recieveremail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55))
        );

        jLabel15.setText("Order No.: ");

        jLabel18.setText("Current Date: ");

        jLabel29.setText("Expected Delivery Date:");

        javax.swing.GroupLayout orderPanelLayout = new javax.swing.GroupLayout(orderPanel);
        orderPanel.setLayout(orderPanelLayout);
        orderPanelLayout.setHorizontalGroup(
            orderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(orderPanelLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(orderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(orderPanelLayout.createSequentialGroup()
                        .addComponent(sendingInstPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(95, 95, 95)
                        .addComponent(orderoptionpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 240, Short.MAX_VALUE)
                        .addGroup(orderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CnclButton, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(invoiceButton, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(orderPanelLayout.createSequentialGroup()
                        .addComponent(SenderPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(orderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(orderPanelLayout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addGap(18, 18, 18)
                                .addComponent(ordernum, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(orderPanelLayout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addGap(18, 18, 18)
                                .addComponent(currentdate, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(orderPanelLayout.createSequentialGroup()
                                .addComponent(jLabel29)
                                .addGap(18, 18, 18)
                                .addComponent(deliverydate, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(173, 173, 173))
            .addGroup(orderPanelLayout.createSequentialGroup()
                .addGap(319, 319, 319)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(custTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(jLabel2)
                .addGap(39, 39, 39)
                .addComponent(MemIdField, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(SearchButton)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(orderPanelLayout.createSequentialGroup()
                .addGap(415, 415, 415)
                .addComponent(RecieverPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(DescrPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        orderPanelLayout.setVerticalGroup(
            orderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(orderPanelLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(orderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(custTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(MemIdField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SearchButton))
                .addGap(37, 37, 37)
                .addGroup(orderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(orderPanelLayout.createSequentialGroup()
                        .addComponent(DescrPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addGroup(orderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ordernum, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15))
                        .addGap(18, 18, 18)
                        .addGroup(orderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18)
                            .addComponent(currentdate, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(orderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(deliverydate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel29, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(orderPanelLayout.createSequentialGroup()
                        .addGroup(orderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(RecieverPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 358, Short.MAX_VALUE)
                            .addComponent(SenderPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(orderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(orderPanelLayout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(sendingInstPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, orderPanelLayout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addGroup(orderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(orderPanelLayout.createSequentialGroup()
                                        .addComponent(invoiceButton)
                                        .addGap(27, 27, 27)
                                        .addComponent(CnclButton))
                                    .addComponent(orderoptionpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(151, 151, Short.MAX_VALUE))
        );

        orderTabbedPane.addTab("New Order", orderPanel);

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel27.setText("Search by Member ID:");

        jLabel28.setText("MemberID: ");

        searchbutton.setText("Search");
        searchbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchbuttonActionPerformed(evt);
            }
        });

        standingTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "OrderNo", "Member ID", "OrderOpt", "Reciever Name", "Reciever Address"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane5.setViewportView(standingTable);

        javax.swing.GroupLayout standingOrderPanelLayout = new javax.swing.GroupLayout(standingOrderPanel);
        standingOrderPanel.setLayout(standingOrderPanelLayout);
        standingOrderPanelLayout.setHorizontalGroup(
            standingOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(standingOrderPanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(standingOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 591, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(standingOrderPanelLayout.createSequentialGroup()
                        .addGroup(standingOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(standingOrderPanelLayout.createSequentialGroup()
                                .addComponent(jLabel28)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(memberidfield, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addComponent(searchbutton)))
                .addContainerGap(644, Short.MAX_VALUE))
        );
        standingOrderPanelLayout.setVerticalGroup(
            standingOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(standingOrderPanelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(standingOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(standingOrderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel28)
                        .addComponent(memberidfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(searchbutton))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(201, Short.MAX_VALUE))
        );

        orderTabbedPane.addTab("Standing Orders", standingOrderPanel);

        RecieverPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Reciever"));

        jLabel30.setText("Name:");

        jLabel31.setText("Phone No:");

        jLabel32.setText("Address:");

        recieveraddr1.setColumns(20);
        recieveraddr1.setRows(5);
        jScrollPane6.setViewportView(recieveraddr1);

        jLabel33.setText("City: ");

        jLabel34.setText("State:");

        jLabel35.setText("E-Mail: ");

        javax.swing.GroupLayout RecieverPanel1Layout = new javax.swing.GroupLayout(RecieverPanel1);
        RecieverPanel1.setLayout(RecieverPanel1Layout);
        RecieverPanel1Layout.setHorizontalGroup(
            RecieverPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RecieverPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(RecieverPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(RecieverPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel30)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(RecieverPanel1Layout.createSequentialGroup()
                        .addGroup(RecieverPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(RecieverPanel1Layout.createSequentialGroup()
                                .addGroup(RecieverPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel31)
                                    .addComponent(jLabel32))
                                .addGap(58, 58, 58)
                                .addGroup(RecieverPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(recipientname1)
                                    .addComponent(recieverphone1)
                                    .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)))
                            .addGroup(RecieverPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel33)
                                .addGap(72, 72, 72)
                                .addGroup(RecieverPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(recievercity1, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                                    .addComponent(recieverstate1)
                                    .addComponent(recieveremail1))))
                        .addContainerGap())
                    .addGroup(RecieverPanel1Layout.createSequentialGroup()
                        .addGroup(RecieverPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel35)
                            .addComponent(jLabel34))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        RecieverPanel1Layout.setVerticalGroup(
            RecieverPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RecieverPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(RecieverPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(recipientname1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(RecieverPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31)
                    .addComponent(recieverphone1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(RecieverPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel32)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(RecieverPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(recievercity1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(RecieverPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel34)
                    .addComponent(recieverstate1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(RecieverPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel35)
                    .addComponent(recieveremail1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36))
        );

        sendingInstPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Sending Instructions"));

        jLabel36.setText("In case of non-delivery:");

        InstrComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Return to sender", "Contact for redirect" }));

        javax.swing.GroupLayout sendingInstPanel1Layout = new javax.swing.GroupLayout(sendingInstPanel1);
        sendingInstPanel1.setLayout(sendingInstPanel1Layout);
        sendingInstPanel1Layout.setHorizontalGroup(
            sendingInstPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sendingInstPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(sendingInstPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel36)
                    .addComponent(InstrComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(98, Short.MAX_VALUE))
        );
        sendingInstPanel1Layout.setVerticalGroup(
            sendingInstPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sendingInstPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel36)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(InstrComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        orderoptionpanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Order Options"));

        OrderbuttonGroup.add(sendRadio1);
        sendRadio1.setText("Send Order Immediately");
        sendRadio1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendRadio1ActionPerformed(evt);
            }
        });

        OrderbuttonGroup.add(StandingRadioButton1);
        StandingRadioButton1.setText("Standing Order");
        StandingRadioButton1.setEnabled(false);
        StandingRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StandingRadioButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout orderoptionpanel1Layout = new javax.swing.GroupLayout(orderoptionpanel1);
        orderoptionpanel1.setLayout(orderoptionpanel1Layout);
        orderoptionpanel1Layout.setHorizontalGroup(
            orderoptionpanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(orderoptionpanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(orderoptionpanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sendRadio1)
                    .addComponent(StandingRadioButton1))
                .addContainerGap(118, Short.MAX_VALUE))
        );
        orderoptionpanel1Layout.setVerticalGroup(
            orderoptionpanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(orderoptionpanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(sendRadio1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(StandingRadioButton1)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jLabel37.setText("Current Date: ");

        jLabel38.setText("Expected Delivery Date:");

        invoiceButton1.setText("Save Order");
        invoiceButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                invoiceButton1ActionPerformed(evt);
            }
        });

        CnclButton1.setText("Cancel");
        CnclButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CnclButton1ActionPerformed(evt);
            }
        });

        jLabel39.setText("Order Id: ");

        searchorder.setText("Search");
        searchorder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchorderActionPerformed(evt);
            }
        });

        deleteorder.setText("Delete Order");
        deleteorder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteorderActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(RecieverPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(69, 69, 69)
                                .addComponent(sendingInstPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(95, 95, 95)
                                .addComponent(orderoptionpanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(99, 99, 99)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(CnclButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(invoiceButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(56, 56, 56)
                                        .addComponent(deleteorder, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(82, 82, 82)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel38)
                                        .addGap(46, 46, 46)
                                        .addComponent(deliverydate1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel37)
                                        .addGap(61, 61, 61)
                                        .addComponent(currentdate1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addComponent(jLabel39)
                        .addGap(32, 32, 32)
                        .addComponent(orderid, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)
                        .addComponent(searchorder)))
                .addContainerGap(117, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel39)
                    .addComponent(searchorder)
                    .addComponent(orderid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addComponent(RecieverPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(271, 271, 271))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sendingInstPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(orderoptionpanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel37)
                    .addComponent(currentdate1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel38, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(deliverydate1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(invoiceButton1)
                    .addComponent(deleteorder))
                .addGap(30, 30, 30)
                .addComponent(CnclButton1)
                .addGap(291, 291, 291))
        );

        orderTabbedPane.addTab("Edit Order", jPanel1);

        SysTabbedPane.addTab("Order Management", orderTabbedPane);

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("Order Id:");

        textSearchID.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N

        buttonGetInvoice.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        buttonGetInvoice.setText("Generate");
        buttonGetInvoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonGetInvoiceActionPerformed(evt);
            }
        });

        buttonSaveInvoice.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        buttonSaveInvoice.setText("View");
        buttonSaveInvoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSaveInvoiceActionPerformed(evt);
            }
        });

        invoicearea.setColumns(20);
        invoicearea.setRows(5);
        jScrollPane4.setViewportView(invoicearea);

        javax.swing.GroupLayout InvoicePanelLayout = new javax.swing.GroupLayout(InvoicePanel);
        InvoicePanel.setLayout(InvoicePanelLayout);
        InvoicePanelLayout.setHorizontalGroup(
            InvoicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InvoicePanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(InvoicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(InvoicePanelLayout.createSequentialGroup()
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(textSearchID, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(buttonGetInvoice, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 880, Short.MAX_VALUE))
                    .addGroup(InvoicePanelLayout.createSequentialGroup()
                        .addComponent(buttonSaveInvoice, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(106, 106, 106)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 729, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        InvoicePanelLayout.setVerticalGroup(
            InvoicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InvoicePanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(InvoicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(textSearchID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonGetInvoice))
                .addGap(44, 44, 44)
                .addGroup(InvoicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonSaveInvoice, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 498, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(174, Short.MAX_VALUE))
        );

        SysTabbedPane.addTab("Invoicing", InvoicePanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(SysTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(180, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(SysTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 790, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RegButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegButtonActionPerformed
        // TODO add your handling code here:
        new RegisterClient().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_RegButtonActionPerformed

    private void ExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new DeliverySystemLogin().setVisible(true);
    }//GEN-LAST:event_ExitButtonActionPerformed

    private void buttonGetInvoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonGetInvoiceActionPerformed
        
        df.generateInvoice(textSearchID.getText());
             
    }//GEN-LAST:event_buttonGetInvoiceActionPerformed

    private void weightordertxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_weightordertxtActionPerformed
        // TODO add your handling code here:
        
        
        
    }//GEN-LAST:event_weightordertxtActionPerformed

    private void senderemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_senderemailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_senderemailActionPerformed

    private void CnclButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CnclButtonActionPerformed
        // TODO add your handling code here:
        new DeliverySystem().setVisible(true);
        
    }//GEN-LAST:event_CnclButtonActionPerformed

    private void custTypeComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_custTypeComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_custTypeComboBoxActionPerformed

    private void MemIdFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MemIdFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MemIdFieldActionPerformed

    private void custTypeComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_custTypeComboBoxItemStateChanged
        // TODO add your handling code here:
       if (custTypeComboBox.getSelectedItem().toString().equals("Member")){
           
           MemIdField.setEnabled(true); 
           StandingRadioButton.setEnabled(true);
       }
    }//GEN-LAST:event_custTypeComboBoxItemStateChanged

    private void invoiceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_invoiceButtonActionPerformed
        df.setCustTypeComboBox(custTypeComboBox.getSelectedItem().toString());
        df.setMemIdField(MemIdField.getText());
        df.setOrdernum(ordernum.getText());
        df.setRecipientname(recipientname.getText());
        df.setRecieverphone(recieverphone.getText());
        df.setSenderaddr(senderaddr.getText());
        df.setSendercity(sendercity.getText());
        df.setSenderemail(senderemail.getText());
        df.setSendername(sendername.getText());
        df.setSenderphone(senderphone.getText());
        df.setSenderstate(senderstate.getText());
        df.setRecieveraddr(recieveraddr.getText());
        df.setRecievercity(recievercity.getText());
        df.setRecieverstate(recieverstate.getText());
        df.setRecieveremail(recieveremail.getText());
        df.setWeightordertxt(Integer.parseInt(weightordertxt.getText()));
        df.setPckgcomboBox(pckgcomboBox.getSelectedItem().toString());  
        df.setGrandtotalLabel(Double.parseDouble(grandtotalLabel.getText()));
        df.setTaxLabel(Double.parseDouble(taxLabel.getText()));
        df.setRatelabel(Double.parseDouble(ratelabel.getText())); 
        df.setGrosstotalLabel(Integer.parseInt(GrosstotalLabel.getText()));
        df.setInstrComboBox(InstrComboBox.getSelectedItem().toString());
        df.setOrderoptions(orderoptions);
        df.setCurrentdate(currentdate.getText());
        df.setDeliverydate(deliverydate.getText());
      
        java.util.Date utilDate = new java.util.Date();
        SimpleDateFormat dft = new SimpleDateFormat("MMM");
        String date3=dft.format(utilDate);
        df.setMonth(date3);
    
        df.order();
        
        
    }//GEN-LAST:event_invoiceButtonActionPerformed

    private void EditButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditButtonActionPerformed
        // TODO add your handling code here:
        new EditClient().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_EditButtonActionPerformed

    private void PayButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PayButtonActionPerformed
        // TODO add your handling code here:
        new PaymentMember().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_PayButtonActionPerformed

    private void searchbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchbuttonActionPerformed
        // TODO add your handling code here:

       df.searchStanding(standingTable,memberidfield.getText());
        
    }//GEN-LAST:event_searchbuttonActionPerformed

    private void sendRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendRadioActionPerformed
        // TODO add your handling code here:
        orderoptions = "Send Order Immediately";
    }//GEN-LAST:event_sendRadioActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        UniqueOrderNumber uin = new UniqueOrderNumber();
        uin.setOrderNum();
        ordernum.setText(uin.getOrderNum());
        
        
        currentdate.setText(d.toString());
        deliverydate.setText(d.plusDays(4).toString());
        
        
        df.setRateComboBox(rateComboBox.getSelectedItem().toString());
        df.setPckgcomboBox(pckgcomboBox.getSelectedItem().toString());
        
                       
           int quota = df.getQuota();
           String quota2= Integer.toString(quota);
           quotalabel.setText(quota2);
            
           int cpkg = df.getRate();
           String costperkg = Integer.toString(cpkg);
           ratelabel.setText(costperkg);
            
            
    }//GEN-LAST:event_formWindowOpened

    private void SearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchButtonActionPerformed
        // TODO add your handling code here:
        
        
        df.searchid(MemIdField.getText());
         
        sendername.setText(df.getSendername());
        senderphone.setText(df.getSenderphone());
        senderaddr.setText(df.getSenderaddr());
        sendercity.setText(df.getSendercity());
        senderstate.setText(df.getSenderstate());
        senderemail.setText(df.getSenderemail());
        rateComboBox.setSelectedItem(df.getRateComboBox());
        
    }//GEN-LAST:event_SearchButtonActionPerformed

    private void StandingRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StandingRadioButtonActionPerformed
        // TODO add your handling code here:
        orderoptions = "Standing Order";
        
        
    }//GEN-LAST:event_StandingRadioButtonActionPerformed

    private void calculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculateActionPerformed
        // TODO add your handling code here:
        
        if(custTypeComboBox.getSelectedItem().toString().equals("Non-member")){
        df.setRateComboBox(rateComboBox.getSelectedItem().toString());
        df.setPckgcomboBox(pckgcomboBox.getSelectedItem().toString());
        
            String w = weightordertxt.getText();
            int weight = Integer.parseInt(w);
            
           int quota = df.getQuota();
           String quota2= Integer.toString(quota);
           quotalabel.setText(quota2);
            
            int cpkg = df.getRate();
            String costperkg = Integer.toString(cpkg);
            ratelabel.setText(costperkg);
            
            int ggross = df.getGross(weight,cpkg);
            String grosstotal = Integer.toString(ggross);
            GrosstotalLabel.setText(grosstotal);
            
            double gtax = df.getTax(ggross);
            String tax = Double.toString(gtax);
            taxLabel.setText(tax);

            double gcost = df.getTotal(ggross,gtax);
            String total_cost = Double.toString(gcost);
            grandtotalLabel.setText(total_cost);
        }

        else{
             df.setRateComboBox(rateComboBox.getSelectedItem().toString());
        df.setPckgcomboBox(pckgcomboBox.getSelectedItem().toString());

            String w = weightordertxt.getText();
            int weight = Integer.parseInt(w);

            df.setRateComboBox(rateComboBox.getSelectedItem().toString());
            
            int cpkg = df.getRate();
            String costperkg = Integer.toString(cpkg);
            ratelabel.setText(costperkg);
            
           int quota = df.getQuota();
           String quota2= Integer.toString(quota);
           quotalabel.setText(quota2);
 
            int ggross = df.getGross(weight,cpkg);
            String grosstotal = Integer.toString(ggross);
            GrosstotalLabel.setText(grosstotal);
 
            double gtax = df.getTax(ggross);
            String tax = Double.toString(gtax);
            taxLabel.setText(tax);
            
            String tc = Double.toString(df.calcPackagePrice(weight, quota, ggross,gtax));

            grandtotalLabel.setText(tc);

        }
    }//GEN-LAST:event_calculateActionPerformed

    private void buttonSaveInvoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSaveInvoiceActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File f =chooser.getSelectedFile();
        String filename = f.getAbsolutePath();
        
        try
        {
            FileReader reader = new FileReader (filename);
            try (BufferedReader br = new BufferedReader(reader)) {
                invoicearea.read(br, null);
            }
            invoicearea.requestFocus();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
        
    }//GEN-LAST:event_buttonSaveInvoiceActionPerformed

    private void viewbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewbuttonActionPerformed
        // TODO add your handling code here:
        c.searchallClient(custTable);
    }//GEN-LAST:event_viewbuttonActionPerformed

    private void searchbyidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchbyidActionPerformed
        // TODO add your handling code here:
        
        c.searchClient(custTable, idtxtbox.getText());
    }//GEN-LAST:event_searchbyidActionPerformed

    private void deleteorderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteorderActionPerformed
        // TODO add your handling code here:
        df.delete(orderid.getText());
    }//GEN-LAST:event_deleteorderActionPerformed

    private void sendRadio1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendRadio1ActionPerformed
        // TODO add your handling code here:
        orderoptions = "Send Order Immediately";
    }//GEN-LAST:event_sendRadio1ActionPerformed

    private void StandingRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StandingRadioButton1ActionPerformed
        // TODO add your handling code here:
        orderoptions = "Standing Order";
    }//GEN-LAST:event_StandingRadioButton1ActionPerformed

    private void invoiceButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_invoiceButton1ActionPerformed
        // TODO add your handling code here:
        df.setOrderid(orderid.getText());
        df.setRecipientname1(recipientname1.getText());
        df.setRecieverphone1(recieverphone1.getText());
        df.setRecieveraddr1(recieveraddr1.getText());
        df.setRecievercity1(recievercity1.getText());
        df.setRecieverstate1(recieverstate1.getText());
        df.setRecieveremail1(recieveremail1.getText());
        df.setInstrComboBox1(InstrComboBox1.getSelectedItem().toString());
        df.setOrderoptions(orderoptions);
        df.setCurrentdate1(currentdate1.getText());
        df.setDeliverydate1(deliverydate1.getText());
        
        java.util.Date utilDate = new java.util.Date();
        SimpleDateFormat dft = new SimpleDateFormat("MMM");
        String date3=dft.format(utilDate);
        df.setMonth1(date3);
        
        
        df.update();
    }//GEN-LAST:event_invoiceButton1ActionPerformed

    private void CnclButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CnclButton1ActionPerformed
        // TODO add your handling code here:
        new DeliverySystem().setVisible(true);
    }//GEN-LAST:event_CnclButton1ActionPerformed

    private void searchorderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchorderActionPerformed
        // TODO add your handling code here
        currentdate1.setText(d.toString());
        deliverydate1.setText(d.plusDays(4).toString());
        
        df.search(orderid.getText());
         
        recipientname1.setText(df.getRecipientname1());
        recieverphone1.setText(df.getRecieverphone1());
        recieveraddr1.setText(df.getRecieveraddr1());
        recievercity1.setText(df.getRecievercity1());
        recieverstate1.setText(df.getRecieverstate1());
        recieveremail1.setText(df.getRecieveremail1());
        
    }//GEN-LAST:event_searchorderActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DeliverySystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DeliverySystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DeliverySystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DeliverySystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DeliverySystem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CnclButton;
    private javax.swing.JButton CnclButton1;
    public javax.swing.JPanel CustrPanel;
    private javax.swing.JPanel DescrPanel;
    private javax.swing.JButton EditButton;
    private javax.swing.JButton ExitButton;
    private javax.swing.JLabel GrosstotalLabel;
    private javax.swing.JComboBox InstrComboBox;
    private javax.swing.JComboBox InstrComboBox1;
    public javax.swing.JPanel InvoicePanel;
    private javax.swing.JTextField MemIdField;
    private javax.swing.ButtonGroup OrderbuttonGroup;
    private javax.swing.JButton PayButton;
    private javax.swing.JPanel RecieverPanel;
    private javax.swing.JPanel RecieverPanel1;
    private javax.swing.JButton RegButton;
    private javax.swing.JButton SearchButton;
    private javax.swing.JPanel SenderPanel1;
    private javax.swing.JRadioButton StandingRadioButton;
    private javax.swing.JRadioButton StandingRadioButton1;
    public javax.swing.JTabbedPane SysTabbedPane;
    private javax.swing.JButton buttonGetInvoice;
    private javax.swing.JButton buttonSaveInvoice;
    private javax.swing.JButton calculate;
    private javax.swing.JLabel currentdate;
    private javax.swing.JLabel currentdate1;
    private javax.swing.JTable custTable;
    private javax.swing.JComboBox custTypeComboBox;
    private javax.swing.JButton deleteorder;
    private javax.swing.JLabel deliverydate;
    private javax.swing.JLabel deliverydate1;
    private javax.swing.JLabel grandtotalLabel;
    private javax.swing.JTextField idtxtbox;
    private javax.swing.JButton invoiceButton;
    private javax.swing.JButton invoiceButton1;
    private javax.swing.JTextArea invoicearea;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTextField memberidfield;
    public javax.swing.JPanel orderPanel;
    public javax.swing.JTabbedPane orderTabbedPane;
    private javax.swing.JTextField orderid;
    private javax.swing.JLabel ordernum;
    private javax.swing.JPanel orderoptionpanel;
    private javax.swing.JPanel orderoptionpanel1;
    private javax.swing.JComboBox pckgcomboBox;
    private javax.swing.JLabel quotalabel;
    private javax.swing.JComboBox rateComboBox;
    private javax.swing.JLabel ratelabel;
    private javax.swing.JTextArea recieveraddr;
    private javax.swing.JTextArea recieveraddr1;
    private javax.swing.JTextField recievercity;
    private javax.swing.JTextField recievercity1;
    private javax.swing.JTextField recieveremail;
    private javax.swing.JTextField recieveremail1;
    private javax.swing.JTextField recieverphone;
    private javax.swing.JTextField recieverphone1;
    private javax.swing.JTextField recieverstate;
    private javax.swing.JTextField recieverstate1;
    private javax.swing.JTextField recipientname;
    private javax.swing.JTextField recipientname1;
    private javax.swing.JButton searchbutton;
    private javax.swing.JButton searchbyid;
    private javax.swing.JButton searchorder;
    private javax.swing.JRadioButton sendRadio;
    private javax.swing.JRadioButton sendRadio1;
    private javax.swing.JTextArea senderaddr;
    private javax.swing.JTextField sendercity;
    private javax.swing.JTextField senderemail;
    private javax.swing.JTextField sendername;
    private javax.swing.JTextField senderphone;
    private javax.swing.JTextField senderstate;
    private javax.swing.ButtonGroup sendingButtongroup;
    private javax.swing.JPanel sendingInstPanel;
    private javax.swing.JPanel sendingInstPanel1;
    public javax.swing.JPanel standingOrderPanel;
    private javax.swing.JTable standingTable;
    private javax.swing.JLabel taxLabel;
    private javax.swing.JTextField textSearchID;
    private javax.swing.JButton viewbutton;
    private javax.swing.JTextField weightordertxt;
    // End of variables declaration//GEN-END:variables
private String orderoptions;

    
}





